apiVersion: apps/v1
kind: Deployment
metadata:
  name: archetype-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: archetype-operator
  template:
    metadata:
      labels:
        name: archetype-operator
    spec:
      serviceAccountName: archetype-operator
      containers:
        - name: archetype-operator
          # Replace this with the built image name
          image: "quay.io/cvicensa/archetype-operator:latest"
          imagePullPolicy: "Always"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "archetype-operator"
